### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by nizyev** [tfredrich/RestApiTutorial.com#19]
Any there any plans to translate web-site into other languages?

**Comment by zzet** [comment]
@imnzv I can help (for example https://github.com/zzet/RestApiTutorial.ru)

**Comment by imnzv** [comment]
@zzet thanks! were looking exactly for Russian translation.

**Comment by tfredrich** [comment]
Thank you very much! I'll add a link to your translation.

**Comment by PlugIN73** [comment]
Cool! @tfredrich thank you! :+1:
