### ISSUE TITLE
Consider including industry practise of REST in the RestApiTutorial.com

### ISSUE THREAD

**Issue by liqian19891011** [tfredrich/RestApiTutorial.com#21]
Hi,

First of all, I want to say that RestApiTutorial.com is really cool, it expresses the REST API principles in a very clear way and I have learned a lot of REST from it. And I think the site will be even better if some **industry practice** of REST be included (sometimes is still hard for developers to directly design a REST API only following the principles)

I'd like to recommend adding **OData** to the website. Below are basic information of OData.
- [OData](http://www.odata.org) -- full name Open Data Protocol is open protocol to allow the creation and consumption of queryable and interoperable RESTful APIs in a simple and standard way.
- OData is an [OASIS standard](https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=odata) that defines the best practice for building and consuming RESTful APIs. And the OData community is working on making OData an ISO standard. OData has been applied in many IT industry leaders including Microsoft, SAP, IBM and [more in the OData ecosystem](http://www.odata.org/ecosystem). 
- OData has detailed and continuing improving [specifications](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html) that covers almost everything in REST principles. 
- Based on the OData protocol, there are various libraries on different platforms supporting building OData service and consuming OData services, see more at http://www.odata.org/libraries .

I definitely DON'T mean to make your site to become another an odata.org site. But I think adding a link in the RestApiTutorial.com or even a separate page with introduction to OData can help developers easily pick up a good and verified practice of REST and start their work directly (since OData has a lot of existing libraries).

**Comment by RainmaKer779** [comment]
Can I work on this?

**Comment by liqian19891011** [comment]
@RainmaKer779  Sure! Glad you can help on this !

**Comment by tfredrich** [comment]
Hi. Sorry I missed this issue.

I do like the concept of "Industry Practices." But it'd be nice if we could add content to the site to clarify the issues you're referring too.

Regarding OData... I'm more on the dislike side of that spec. It's not RESTful, reflects the underlying database schema, is insecure and is not recommended.  We should pick industry best practices to illustrate.
