### ISSUE TITLE
Reference OData in the Resources page?

### ISSUE THREAD

**Issue by dingeins** [tfredrich/RestApiTutorial.com#28]
Hi,

I wonder if it'd be useful for RestApiTutorial.com visitors to reference OData related information in its [Resource page](http://www.restapitutorial.com/resources.html).

OData is the short for the Open Data Protocol. It's a open industry standard approved by OASIS (ref: https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=odata). It provides specifications and guidelines about how to build and consume REST APIs (URL conventions, behavioral specifications, schema exposure, control information exposure, etc.).

It represents industry practices as Microsoft, SAP, Salesforce, IBM and etc. are all adopting OData as their REST API guidelines. 

For more info about it you may refer to http://www.odata.org/.

**Comment by tfredrich** [comment]
Thanks for your suggestion. I want to be sensitive to your efforts on OData, but also want to explain a little bit about why I'm choosing not to reference it on the resource page.

REST API best practices follow a resource-driven, design-first approach taking into account the resources, media types and hypermedia relationships involved, carefully ensuring applicability and usability.

OData exposes low-level data tables through HTTP via URLs, largely removing that design-first element. Like any general-purpose tool, it may be useful, but not directly applicable to what we're talking about here.
