### ISSUE TITLE
Httpmethods page has error in initial load

### ISSUE THREAD

**Issue by tomkuijsten** [tfredrich/RestApiTutorial.com#30]
When opening the httpmethods page, the "more detailed" discussion shows the GET, but the POST header is selected.

**Comment by flyingfisch** [comment]
What browser are you using? In Firefox the POST header is selected, and the content is also the POST description.

**Comment by tomkuijsten** [comment]
I tried reproducing it, but I can't. Something fixed?

**Comment by flyingfisch** [comment]
Maybe, but I guess it's up to @tfredrich to make that call and close this issue.

**Comment by tfredrich** [comment]
Thanks. Fixed. Please try it again.
