### ISSUE TITLE
Any guidelines on handling parameter arrays?

### ISSUE THREAD

**Issue by tomkuijsten** [tfredrich/RestApiTutorial.com#34]
I was wondering if there were any guidelines on parameter arrays in a REST api call.

Eg I want to pass an array of id's to get a list of parameters. Two possible implementations:
GET /api/parameters/[1,2,3,4]
or
GET /api/parameters/ids[]=1&ids[]=2&ids[]=3&ids[]=4

**Comment by IlianIliev** [comment]
As far as I know there is no proposed official way to do it in the HTTP RFC.
I think the option that is most widely used by frameworks and developers is just to pass multiple same-named parameters with different values and then hope that the APP/Framework will parse them according to your desire.

**Comment by tomkuijsten** [comment]
I don't follow, you mean to support something like this:

GET /api/parameters/1/parameters/2/parameters/3/parameters4

**Comment by IlianIliev** [comment]
No, I mean like

GET /resource/1?id=1&id=2&id=3

If I remember correctly the "[]" thing was the PHP way to handle multiple values with the same way.

**Comment by tomkuijsten** [comment]
Ah ok, I get it. But isn't the [ ] thing the way that a html form formats the url on a get?

**Comment by tfredrich** [comment]
Ah. Interesting. True there is no defacto convention here. In my head, if we follow the "collection metaphor" this is a filter scenario. We would then end up with a filter on the collection resource like so:

GET /users?filter=id::1,2,3,4

GET /users?id=1&id=2&id=3&id=4

would also work, but ends up being a lot more verbose (suppose you want 50 or more?). Also, if you want to support something like "(id > 0 && id < 5)" you can't do it with plain-old query parameters unless you support the 'filter' concept.

See pg. 27 of the PDF best practices guide for an explanation why the 'filter' query-string parameter (if you're interested) https://github.com/tfredrich/RestApiTutorial.com/raw/master/media/RESTful%20Best%20Practices-v1_2.pdf

**Comment by IlianIliev** [comment]
@tfredrich I am not really fond of the first options. The reason is that if you have to pass strings, but not integers you might have something like 'my, string' and then you need to come up with some weird custom separator.
