### ISSUE TITLE
Switch bootstrap CDN

### ISSUE THREAD

**Issue by amyhickman** [tfredrich/RestApiTutorial.com#36]
My corporate firewall blocks https://d7im4lln3lvbg.cloudfront.net.  Can you switch to another CDN, such as https://www.bootstrapcdn.com/ ?

Thank you for your consideration.

**Comment by tfredrich** [comment]
Thanks for the suggestion. Switched. Try it now.

**Comment by amyhickman** [comment]
Thank you very much!
