### ISSUE TITLE
Non responsive web pages

### ISSUE THREAD

**Issue by ghost** [tfredrich/RestApiTutorial.com#47]
I found that there are some pages those are not responsive for phone or small devices.
Screenshots are attached:
![screenshot_20171111-140356](https://user-images.githubusercontent.com/22418759/32687758-8b5131b2-c6e9-11e7-8afb-0a9bc7415242.png)

Another:

![screenshot_20171111-140347](https://user-images.githubusercontent.com/22418759/32687764-ae3d580e-c6e9-11e7-8b8e-c880d30cb555.png)

I have fixed them so can it be merged?

**Comment by tfredrich** [comment]
Thanks for reaching out. It should be much better now after refactoring to the new theme.
